name: Build

on:
  push:
    branches: [ main, master ]
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: setup-jdk-21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribuition: 'temurin'
          cache: maven
      - name: build-maven
        run: mvn -B package --file pom.xml