name: Pipeline Template

on:
  push:
    branches: [ main, master ]
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      #message:
      #  required: false
      #  type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: unit-test
        run: echo "unit test" #TODO
  build:
    needs: test
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      maven_version: ${{ steps.maven_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: setup-jdk-21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: build-maven
        run: mvn clean package
      - name: mave-get-version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        id: maven_version
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0
      - name: docker-login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build
        run: echo "docker build" #TODO
      - name: docker-tag
        run: echo ${{ needs.build.outputs.maven_version }}
