name: Pipeline Template

on:
  push:
    branches: [ main, master ]
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
      #message:
      #  required: false
      #  type: string

jobs:
  #todo: test
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: setup-jdk-21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: build-maven
        run: mvn clean package
  #qodana:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #    checks: write
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        ref: ${{ github.event.pull_request.head.sha }}
  #        fetch-depth: 0
  #    - name: 'Qodana Scan'
  #      uses: JetBrains/qodana-action@v2025.2
  #      env:
  #        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  #      with:
  #        # In pr-mode: 'true' Qodana checks only changed files
  #        pr-mode: false
  #        use-caches: true
  #        post-pr-comment: true
  #        use-annotations: true
  #        # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
  #        upload-result: false
  #        # quick-fixes available in Ultimate and Ultimate Plus plans
  #        push-fixes: 'none'
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          #registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
